[build]
builder = "RAILPACK"
buildCommand = "vp build"

[deploy]
preDeployCommand = "pnpm run db:migrate"
runtime = "V2"
numReplicas = 1
startCommand = "pnpm start"
healthcheckPath = "/"
useLegacyStacker = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
