[build]
builder = "RAILPACK"
buildCommand = "vp run build"

[deploy]
preDeployCommand = "vp run db:migrate"
runtime = "V2"
numReplicas = 1
startCommand = "vp run start"
healthcheckPath = "/"
useLegacyStacker = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
